default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: postgres
  password: postgres
  database: whatiswrong_development
  host: db

test:
  <<: *default
  username: postgres
  password: postgres
  database: whatiswrong_test
  host: db

production:
  <<: *default
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
